name: Subete
main: uk.co.hubza.subetemain.subetemain
version: 1.0

commands:
   subete:
      description: About Subete
      usage: /subete
      permission: SubeteMain.subete
      permission-message: You don't have <permission>
   subetepl:
      description: Plugins and stuff
      usage: /subetepl
      permission: SubeteMain.subete
      permission-message: You don't have <permission>

permissions:
    SubeteMain.subete:
        description: Subete Main message